### ISSUE TITLE
Redshift Destination

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#101]
This ticket is to add Amazon Redshift as a destination.

Documentation for the go client library is here: https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/ but it's also accessible via `database/sql` as a Postgres database

Localstack implementation docs are here: https://docs.localstack.cloud/user-guide/aws/redshift/

- Implement the DatabaseServer interface
- Inserts should happen via `COPY`

**Comment by sd1li** [comment]
@poundifdef It turns out this issue referred to BigQuery. Let me know if I missed any important detail.

**Comment by poundifdef** [comment]
Superseded by #117
