### ISSUE TITLE
Running ./scratchdata  

### ISSUE THREAD

**Issue by mrayva** [scratchdata/scratchdata#109]
Please help locating scratchdata  within scratchdb_Linux_x86_64.tar

**Comment by poundifdef** [comment]
Thank you for this - and I apologize for the confusion!

Right now, your best bet to run the software is to follow the instructions in the README file and adjust the example config file. This is being used in production today. I am _actively_ working on launching the v2 branch which has many improvements over the current main. The documentation on the website reflects the v2 code, but I am still finalizing the launch and updating the release process. 

I'm happy to help get the v1 code up and running, feel free to continue in this issue.

**Comment by poundifdef** [comment]
@mrayva Hi - you should now be able to download the latest release and it should contain the `scratchdata` binary in the documentation. Please let me know if you have any other issues!
