### ISSUE TITLE
Compress data as it is streamed

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#11]
We could compress data using a gzip writer or brotli writer (https://pkg.go.dev/github.com/andybalholm/brotli#NewWriter) as it streams in for efficiency. this could be configurable too.

**Comment by Sharath-majjigi** [comment]
Hey can you provide more context to this I want to work on this.

**Comment by poundifdef** [comment]
When new data is inserted, we append it to a file here: https://github.com/scratchdata/ScratchDB/blob/main/ingest/writer.go#L305

Instead of using a regular writer, we could instead append to a gzip or brotli file for compression. The requirements would be:

- Have a configuration option to choose how to compress
- Use a streaming writer
- When we consume these files, make sure we handle the compression method. 
- We want the _uncompressed_ data to have a limit (say, 1 GB) so we don't accidentally fill a disk when decompressing files
