### ISSUE TITLE
Create cross-platform releases with CGO enabled

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#111]
We want a github action which will cross-compile the package when a new tag is pushed and create a github release with the artifacts. 

- The package uses cgo modules, so we must be able to cross-compile for other platforms. This is probably done most easily with docker containers.
- We may use goreleaser for this. I have an example goreleaser file already but it does not work for cross-compilation. However, we are not required to use goreleaser.
- We already have the start of a github workflow, `release.yml` which uses goreleaser. You will want to modify this.

**Comment by ezhil56x** [comment]
/attempt #111
Can I get this assigned?

**Comment by Bhavyajain21** [comment]
Can I be assigned?
