### ISSUE TITLE
Sharable URLs for Querying Data

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#116]
Today, you can query the API by calling an endpoint like so:

```
http://localhost:8080/api/data/query?api_key=local&query=select * from events" 
```

We want to be able to create "sharable URLs." This is how it should work:

## New Endpoint

- [ ] Create a new POST endpoint for creating a query. It should be `POST /api/data/query/share?api_key=local`. The query should be part of the POST request body.
- [ ] The POST request body should also take a duration, which is the number of seconds for the link to be valid for.
- [ ] This endpoint should be authenticated via API key
- [ ] The return value should be a new UUID which represents the query.

## Save query to cache

- [ ] We have a cache [interface](https://github.com/scratchdata/scratchdata/blob/main/pkg/storage/cache/cache.go) which has no implementation. Implement an in-memory cache. You may use a library such as https://github.com/eko/gocache
- [ ] The cache key should be a UUID. 
- [ ] The cache value should store the database ID and query. It should also respect the expiration directive.

## Endpoint to Query Data

- [ ] Create a new endpoint: `GET /share/<uuid>/data.<format>`
- [ ] This endpoint should not be authenticated
- [ ] It should run the query for the given `<uuid>` and return the format specified by `<format>`. This will either be `csv` or `json`. 
- [ ] You should refactor the existing [Select endpoint](https://github.com/scratchdata/scratchdata/blob/main/pkg/api/data.go#L14) in order to reuse code for streaming data to the client

**Comment by abhishek818** [comment]
@poundifdef  Can i get this assigned, will give it a try this weekend..

**Comment by mohanish2504** [comment]
@poundifdef will liek to add my name for attempt
