### ISSUE TITLE
move frontend into repo

### ISSUE THREAD

**Issue by breadchris** [scratchdata/scratchdata#136]
Currently, the front end is in another repo and should be moved over to this one. 

There are currently multiple versions of the frontend, svelte and HTML templates. Go HTML templates with tailwindcss have been chosen as the tech to use moving forward.

Questions:
- Should the svelte code also come over for reference, or should it be kept in the other repo? Answer seems like it should be kept where it is and only relevant code comes over.

![Screenshot 2024-03-25 at 1 01 30 PM](https://github.com/scratchdata/scratchdata/assets/1069294/cea4e531-e8c7-4d25-a3b8-e27c271478e0)

**Comment by poundifdef** [comment]
Agree, no need to bring over the svelte code.
