### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#18]
Create API keys with permissions
- read only
- read/write
- filtered by table, user, row

**Comment by NamanAg0502** [comment]
Hey @poundifdef,

I would like to contribute to the ScratchDB project. Can you please provide me with some resources or a guide to help me get started?

I understand that the project involves wrapping a Postgres database with ScratchDB, and then organizing, filtering, and managing the data before pushing it to ClickHouse for storage. Is that correct?

I applied for a beta API key, but I received the following error message:

<img width="1103" alt="Api Error Image" src="https://github.com/scratchdata/ScratchDB/assets/76512364/bc3f0391-caab-4ff3-be41-0297f424f7e5">

Could you please help me with this?

Thanks,
[Your name]
