### ISSUE TITLE
/v1/input/<api_key> for datadog compatibility

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#4]
In order to be compatible with DataDog for log ingest, we should support a `/v1/input` endpoint. We should also investigate DataDog's v2 endpoint schema.

**Comment by tanmaymunjal** [comment]
Hey @poundifdef, looking at the documentation for Datadog(https://docs.datadoghq.com/api/latest/logs/?code-lang=go), it seems that the main difference between /v1/input and /v2/logs is that the v2 version takes in extra parameters in the body as hostname, service, and source while the v1 version only takes as input ddtags and message.

I think it makes sense to add both to the API to allow for compatibility with Datadog API clients. What do you think about it?
Would love to work on it, could you please assign me the issue?

**Comment by poundifdef** [comment]
Thanks for taking an interest in this issue. Please feel free to make a PR.

One thing to consider is how to namespace the endpoint. Ideally there would
be a url prefix such as /datadog/v1 or something, but many exporters only
let you specify a base url. Should there be a configuration option to
enable this?

**Comment by tanmaymunjal** [comment]
Hmmm, we could set a configuration option that sets the endpoint for this perhaps. Not sure if it's the best route though. Will look into this a bit more.
