### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#8]
Dashboard to see usage, billing, etc

**Comment by siddharth-sable** [comment]
Hello @poundifdef, I would love to work on this.

**Comment by poundifdef** [comment]
Hello, thank you for the offer! I'd be happy for the help. Since there is no UI yet, here are some ideas on how to get started:

- Everything should compile into a single Go binary
- If you want to build a SPA, then I'd suggest using SvelteKit. Otherwise plain server-rendered HTML is fine.
- The goal is to keep the UI as simple and lightweight as possible
- We will need a way to log in via Google OAuth
- We will want the ability to enable or disable the UI via a flag in the configuration file

Once we have some basic scaffolding, then we can talk about the features we'd want to build within the dashboard. I'd be happy to hear your gameplan before you get started coding.

Thanks again!

**Comment by manpoffc** [comment]
Hello,
I would love to take the initiative and discuss more on the design and implementation of the UI.
