### ISSUE TITLE
Postgrest Syntax Support

### ISSUE THREAD

**Issue by poundifdef** [scratchdata/scratchdata#97]
It would be great to support a subset of the [Postgrest](https://postgrest.org/en/stable/) syntax. This ticket is to implement basic query support for Clickhouse.

There is a skeleton here, which includes the start of a parser and scaffolding: https://github.com/scratchdata/ScratchDB/pull/96

The goal of this ticket is to be able to support the section "Column Filters" in this [document](https://docs.google.com/document/d/1pHwrCKpkSgO4HnNfGmUEAdHamQlhLgvIcPE4__RGFJQ/edit).

The above draft pull request already parses the query into a struct. Now the code just needs to parse that struct, create a SQL statement, and perform the query.

For this iteration, do not implement other types of filters, such as AND, OR, or limit/offset. Assume the query is just `SELECT * WHERE ...` and we will be implementing the WHERE clause for different parameters.

**Comment by chumaumenze** [comment]
@sd1li, I see you opened PR #99 for this. I will reassign this to you.
